- hosts: "43.205.210.13"
  tasks:
  - get_url:
      url: "https://get.docker.com"
      dest: "/root/get-docker.sh"
  - file:
      path: "/root/get-docker.sh"
      mode: "0777"
  - shell: "/root/get-docker.sh"
  - docker_image:
      name: "alpine:latest"
      source: "pull"
  - docker_container:
      name: "my-apline"
      image: "alpine:latest"
      state: "started"
      ports:
        - "8081:80"
      command: "sh -c 'while true; do echo \"HTTP/1.1 200 OK\" | nc -l -p 80 -q 1; done'"
