- hosts: "43.205.210.13"
  tasks:
  - get_url:
      url: "https://get.docker.com"
      dest: "/root/get-docker.sh"
  - file:
      path: "/root/get-docker.sh"
      mode: "0777"
  - shell: "/root/get-docker.sh"
  - docker_image:
      name: "alpine:latest"
      source: "pull"
  - docker_container:
      name: "my-apline"
      image: "alpine:latest"
      state: "started"
      ports:
        - "80:8080"
