- hosts: "all"
  gather_facts: no
  tasks:
  - file:
      state: directory
      path: "/tmp/dvd2"
  - mount:
      src: "/dev/xvdf"
      path: "/tmp/dvd2"
      state: "mounted"
      fstype: "tmpfs"
