- hosts: "all"
  tasks:
  - file:
      state: directory
      path: "/dvd1"
  - mount:
      # src: "/dev/cdrom"
      src: "/dev/loop8"
      path: "/dvd1"
      state: "mounted"
      fstype: "iso9660"